# docker-compose.yml

services:
  db:
    image: postgres:16.8
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
      TZ: 'Europe/Kyiv'
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Оголошуємо "том", щоб Docker міг ним керувати
volumes:
  postgres_data: